#!/bin/bash

cd /srv/app

python3 manage.py runserver 127.0.0.1:8000 &

myip=$(hostname -I | awk '{print$1}')
export ALLOWED_HOSTS=$(hostname -I | awk '{print$1}')
sed -e "s|server_name localhost|server_name ${myip}|g" -i /etc/nginx/sites-available/app

systemctl restart nginx

# Remove the ssh force logout command
sed -e '/Match User root/d' -e '/.*ForceCommand.*droplet.*/d' -i /etc/ssh/sshd_config

systemctl restart ssh
